fix: workflow jobs

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -8,4 +8,14 @@ jobs:
     echo-hello:
         runs-on: ubuntu-latest
         steps:
-            - run: echo "Say hello"
+            - name: Say Hello
+              run: echo "Say hello"
+    echo-goodbey:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Failed step
+              run: |
+                echo "I will fail"
+                exit 1
+            - name: Say goodbey
+              run: echo "Goodbey!"
